name: chatapp
description: A new Flutter project.

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  font_awesome_flutter: ^8.10.0
  firebase_auth: ^0.16.1
  google_sign_in: ^4.5.1
  shared_preferences: ^0.5.8
  cloud_firestore: ^0.13.7
  international_phone_input: ^1.0.4
  pin_code_fields: ^4.0.0
  flutter_svg: ^0.17.1
  firebase_storage: ^3.1.6
  image_picker: ^0.6.7+12
  image_cropper: ^1.3.1
  date_format: ^1.0.8
  chips_choice: ^1.2.0
  cupertino_icons: ^0.1.3


dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true
  assets:
    - assets/
  fonts:
    - family: GoogleSans
      fonts:
        - asset: assets/Fonts/GoogleSans-Regular.ttf
        - asset: assets/Fonts/GoogleSans-Bold.ttf
